"""empty message

Revision ID: 5341c9f1e287
Revises: 
Create Date: 2017-10-07 16:51:37.452830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5341c9f1e287'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('asb', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'author_id')
    op.drop_column('comments', 'asb')
    # ### end Alembic commands ###
